### PR TITLE
Update Slovak translation

### PR DESCRIPTION
**Pull request by Svec-Tomas**
Translated the new tooltips strings

### CODE REVIEW

**Comment by pakerwreah** [comment]
There's a new one:
`//"calendars.source.others" = "Others";`

Could you translate it as well?

**Review by pakerwreah — APPROVED** [review]

**Comment by Svec-Tomas** [comment]
> There's a new one: `//"calendars.source.others" = "Others";`
> 
> Could you translate it as well?

Sure, but what's the right way to do it now, please? I see it is approved, but I don't see my previous translation implemented here yet:

https://github.com/pakerwreah/Calendr/blob/master/Calendr/Assets/sk.lproj/Localizable.strings

**Comment by Svec-Tomas** [comment]
> ChatGPT told me "Iné" was a good fit, do you agree?

It would be in most cases a correct translation, but here it is "Ostatné", just double checked with Apple Calendar as well:

CleanShot 2024-11-11 at 20 07 07@2x

**Comment by pakerwreah** [comment]
For you to keep editing the file from a PR, you just go to the last tab "Files changed", tap the 3 dots and "Edit file".

Files changed|Edit file
--|--
Screenshot 2024-11-11 at 19 05 25|Screenshot 2024-11-11 at 19 06 11

Try to fix my mistake by doing that.

**Comment by Svec-Tomas** [comment]
While we speak about Calendars, do you have maybe any idea from where this Subscribed Calendars string comes from?

I do not see it in my Apple Calendar for example, but it is present in Calendr.

CleanShot 2024-11-11 at 20 09 27@2x

**Comment by pakerwreah** [comment]
That comes from Apple's imagination 🤣

The subscribed calendars will now be under the "Others" section, with a "wave" icon next to it, like the one we have in the native app.

**Comment by pakerwreah** [comment]
I think you missed a "t" though, I'm gonna fix it on the main branch.

**Comment by Svec-Tomas** [comment]
> I think you missed a "t" though, I'm gonna fix it on the main branch.

Hahaha, you are right, you have an eagle eye! 👍

**Pull request merged**
